service: aws-http-api-ts
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: cn-northwest-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  serverless-offline:
    # ignoreJWTSignature: true
    noPrependStageInUrl: true
    noAuth: true
