service: aws-http-api-ts-esbuild
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: cn-northwest-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          authorizer: 
            type: aws_iam          
plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    sourcemap: true
  serverless-offline:
    noPrependStageInUrl: true
    noAuth: true